#!/bin/bash
if [ $# -ne 1 ];
then
  echo "asmlg <input.mix>"
  exit 1
fi

asminp=$1
inp=$(basename $asminp .mix)
inp5=$(echo $asminp | cut -c -5)

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK STARTED *************************"
echo
echo "==============================================================="
echo "ASSEMBLY LISTING: $inp.prn"
echo "      TRANS DECK: $inp5.tra"
echo "==============================================================="
echo

rm -f $inp5.tra
./mix -a $asminp -p 2>&1 | tee $inp.prn

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK ENDED **************************"
echo

