#!/bin/bash
if [ $# -ne 1 ];
then
  echo "asmlg <input.mix>"
  exit 1
fi

asminp=$1
inp=$(basename $asminp .mix)
inp5=$(echo $asminp | cut -c -5)

rm -f $inp5.tra
./mix -a $asminp -p 2>&1 | tee $inp.prn

rm -f printer
cat cardload.dek $inp5.tra >reader

if [ ! -z $MIXTRACE ];
then
  ./mix -t $MIXTRACE -g > $inp.tre 2>&1
else
  ./mix -g 2>&1 | tee $inp.tre
fi

if [ -s printer ];
then
  cp printer $inp.log
fi
