#!/bin/bash
if [ $# -ne 1 ];
then
  echo "asmlg source[.mix]"
  exit 1
fi

inp=$1

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK STARTED *************************"
echo
echo "==============================================================="
echo "ASSEMBLY LISTING: $inp.prn"
echo "      TRANS DECK: $inp.tra"
echo "==============================================================="
echo

rm -f $inp.prn
rm -f $inp.tra
rm -f $inp.sym

./mix -a $inp.mix -y $inp.sym -p 2>&1 | tee $inp.prn

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK ENDED **************************"
echo

