#!/bin/bash

if [ $# -ne 1 ];
then
  echo "asmlg <input.mix>"
  exit 1
fi

inp=$1

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASMLG TASK STARTED ************************"
echo
echo "==============================================================="
echo "    TRACE OUTPUT: $inp.tre"
echo "     PRINTER LOG: $inp.log"
echo "==============================================================="
echo

rm -f $inp.tre
rm -f $inp.log

rm -f printer

./asml $inp

if [ -s $inp.tra ];
then
  cat cardload.dek $inp.tra >reader
  if [ ! -z $MIXTRACE ];
  then
    ./mix -t $MIXTRACE -g > $inp.tre 2>&1
  else
    ./mix -g 2>&1 | tee $inp.tre
  fi

  if [ -s printer ];
  then
    cp printer $inp.log
  fi
else
  echo "$inp.tra not found"
fi

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASMLG TASK ENDED **************************"
echo
