#!/bin/bash
if [ $# -ne 1 ];
then
  echo "asmlg <input.mix>"
  exit 1
fi

inp=$1

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK STARTED *************************"
echo
echo "==============================================================="
echo "ASSEMBLY LISTING: $inp.prn"
echo "      TRANS DECK: $inp.tra"
echo "==============================================================="
echo

rm -f $inp.prn
rm -f $inp.tra

if [ ! -z $MIXTRACE ];
then
  ./mix -t $MIXTRACE -a $inp.mix -p 2>&1 | tee $inp.prn
else
  ./mix -a $inp.mix -p 2>&1 | tee $inp.prn
fi

TS=$(date +%Y%m%d-%H%M%S)
echo
echo "*** $TS ASML TASK ENDED **************************"
echo

